# Generated by Django 3.2.4 on 2022-12-12 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prodavac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=55)),
                ('porucivanje', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['porucivanje'],
            },
        ),
        migrations.CreateModel(
            name='Artikal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
                ('opis', models.TextField()),
                ('slika', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(max_length=55)),
                ('datum_dodavanja', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artikli', to='artikal.kategorija')),
                ('prodavac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artikli', to='prodavac.prodavac')),
            ],
            options={
                'ordering': ['-datum_dodavanja'],
            },
        ),
    ]
