# Generated by Django 3.2.4 on 2022-12-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikal', '0003_alter_artikal_kolicina_na_stanju'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikal',
            name='nema_na_stanju',
            field=models.BooleanField(default=False),
        ),
    ]
