# Generated by Django 3.2.4 on 2022-12-12 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prodavac', '0001_initial'),
        ('artikal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porudzbenica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('adresa', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('mesto', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=100)),
                ('napravljena', models.DateTimeField(auto_now_add=True)),
                ('placen_iznos', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prodavci', models.ManyToManyField(related_name='porudzbenice', to='prodavac.Prodavac')),
            ],
            options={
                'ordering': ['-napravljena'],
            },
        ),
        migrations.CreateModel(
            name='PoruceniArtikal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodavac_platio', models.BooleanField(default=False)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=8)),
                ('kolicina', models.IntegerField(default=1)),
                ('artikal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stvari', to='artikal.artikal')),
                ('porudzbenica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stvari', to='porudzbenica.porudzbenica')),
                ('prodavac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stvari', to='prodavac.prodavac')),
            ],
        ),
    ]
